parameters:
  easy_redirect.remove_not_found_subscriber.class: Adeliom\EasyRedirectBundle\EventListener\Doctrine\RemoveNotFoundSubscriber

services:

  easy_redirect.remove_not_found_subscriber:
    class: "%easy_redirect.remove_not_found_subscriber.class%"
    arguments:
      - '@easy_redirect.not_found_manager'
    tags:
      - { name: 'doctrine.event_listener', event: 'postPersist' }
      - { name: 'doctrine.event_listener', event: 'postUpdate' }
